[application]
#ca_certificate_file = ~/.gateway.d/certificates/ca.pem
mode                 = client
working_dir          = /root/.gateway.d

[client]
#certificate_file = ~/.gateway.d/certificates/client.pem
host              = gateway5
#port             = 50051
#private_key_file = ~/.gateway.d/certificates/client-key.pem
use_tls           = false

[log]
#level = INFO
